services:
    # Web service
    - type: web
      name: emailengine
      env: node
      repo: https://github.com/hugo082/emailengine.git
      plan: free
      numInstances: 1
      #healthCheckPath: /health
      buildCommand: ./update-info.sh && npm install --omit=dev
      startCommand: npm start
      envVars:
          - key: EENGINE_REDIS
            fromService:
                type: redis
                name: ee-redis
                property: connectionString
          - key: EENGINE_SECRET
            generateValue: true
          - key: EENGINE_WORKERS
            value: 1
          - key: EENGINE_WORKERS_WEBHOOKS
            value: 1
          - key: EENGINE_WORKERS_SUBMIT
            value: 0
          - key: EENGINE_TIMEOUT
            value: 30s
          - key: EENGINE_HOST
            value: 0.0.0.0
          - key: EENGINE_API_PROXY
            value: 1
          - key: EENGINE_MAX_SIZE
            value: 25M
          - key: EENGINE_IMAP_PROXY_ENABLED
            value: false
      autoDeploy: false # optional

    # The Redis instance
    - type: redis
      name: ee-redis
      ipAllowList: []
      plan: free
      maxmemoryPolicy: noeviction # optional (defaults to allkeys-lru)
